version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - observability-elk
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.12.0
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - observability-elk
  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.0
    command: logstash -f /usr/share/logstash/config/logstash.conf
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/config/logstash.conf:ro
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    ports:
      - 12201:12201/udp
    networks:
      - observability-elk
networks:
  observability-elk:
    driver: bridge
volumes:
  elasticsearch-data-volume:
