spring:
  h2:
    console:
      enabled: "true"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
  datasource:
    username: "sa"
    password: "changeme"
    driverClassName: "org.h2.Driver"
    url: "jdbc:h2:mem:jpadb"
logstash:
  host: ${LOGSTASH_HOST:localhost}